### ISSUE TITLE
Calculated P Gains are incorrect

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/sysid#125]
![image](https://user-images.githubusercontent.com/10674555/116723897-f7fe3300-a9ad-11eb-870a-455a46eec100.png)

![image](https://user-images.githubusercontent.com/10674555/116724436-a6a27380-a9ae-11eb-8ebe-056a4fa4535a.png)

**JSON**: [characterization-data20210429-2325_new.json.txt](https://github.com/wpilibsuite/sysid/files/6406675/characterization-data20210429-2325_new.json.txt) and units per rotation are 0.219915

My actual P gain that worked was around ~11.7, anything large than 13 created oscillations.

**Comment by prateekma** [comment]
You should tweak the "Max Velocity Error" setting to a desired value. In your case, 1.5 m/s is a lot of error. Setting it to 0.2 or 0.3 m/s gives values closer to what you are looking for.
