### ISSUE TITLE
Median Filter Time offset for certain datasets

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#132]
For a particularly noisy dataset, the median filter seems to have gotten the timestamps shifted.

![image](https://user-images.githubusercontent.com/29788153/117550636-04fed000-b007-11eb-8916-9afb66e2edc4.png)

**Comment by calcmogul** [comment]
Could you post the JSON that's from so it can be reproduced?

**Comment by Piphi5** [comment]
[sysid_data20210319-1614.json.txt](https://github.com/wpilibsuite/sysid/files/6446444/sysid_data20210319-1614.json.txt)
