### ISSUE TITLE
Weird end behavior for some of the simulation graphs

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#146]
I loaded the data from #74 and it looks like the simulation is quite off towards the end:
![image](https://user-images.githubusercontent.com/29788153/119864828-a7acbf00-bee0-11eb-9ff5-6a78e5e7e559.png)

**Comment by calcmogul** [comment]
That's because Ka < 0.

**Comment by Piphi5** [comment]
Yeah, somethings messing with that kA fit since its clearly >0

**Comment by calcmogul** [comment]
I thought the broken fit was caused by the velocity spikes at the beginning of the quasistatic tests.
![Screenshot_2021-06-02_23-09-03](https://user-images.githubusercontent.com/2748555/120595669-9c352880-c3f7-11eb-9526-cb2b31619e27.png)

This printed removals, but didn't seem to help:
```cpp
  // Remove data with velocity spikes
  sysid::ApplyToData(
      preparedData,
      [&](std::string_view key) {
        auto& data = preparedData[key];

        data.erase(std::remove_if(
                       data.begin(), data.end(),
                       [=](const auto& pt) {
                         if (std::abs(pt.velocity - pt.nextVelocity) > 25.0) {
                           fmt::print(stderr, "{}: FOUND with {}\n", key,
                                      std::abs(pt.velocity - pt.nextVelocity));
                         }
                         return std::abs(pt.velocity - pt.nextVelocity) > 25.0;
                       }),
                   data.end());
      },
      [](std::string_view key) {
        return key.find("raw") == std::string_view::npos;
      });
```

**Comment by Piphi5** [comment]
That is incredibly weird... Would it be safe to assume that data wouldn't get that messy? Also, why doesn't the median filter reject the outlier?

**Comment by calcmogul** [comment]
I think something's wrong with the data collection itself.

**Comment by Piphi5** [comment]
Probably with how the user set it up yeah

**Comment by Piphi5** [comment]
This seems to be more of an issue with the collected data from the frc-char tool than an issue with sysid.
