### ISSUE TITLE
Program crashes when loading data file

### ISSUE THREAD

**Issue by willtoth** [wpilibsuite/sysid#175]
Attached the data file. This was saved after doing all 4 tests. 

[sysid_data20210822-104822.zip](https://github.com/wpilibsuite/sysid/files/7027725/sysid_data20210822-104822.zip)

I don't see any kind of log or other information that I can include here, is there a way to generate debugging info?

**Comment by Piphi5** [comment]
Running the repository with gradle opens up a debug version and there are python plotting scripts of the data. 

I went ahead and ran the debug version and it didn't crash when opening your data. However, the graphs are definitely suspect of something going very wrong.
![image](https://user-images.githubusercontent.com/29788153/130363246-b01dd41b-95c1-48dd-b428-afbbd9494576.png)
![image](https://user-images.githubusercontent.com/29788153/130363252-0508dacc-5677-49d0-be01-3a32e171ee5b.png)
![image](https://user-images.githubusercontent.com/29788153/130363254-04622e83-919d-40a4-a329-cdb77ddc7631.png)
![image](https://user-images.githubusercontent.com/29788153/130363260-7dc49579-4d84-48fc-b596-1d3a69f65838.png)
![image](https://user-images.githubusercontent.com/29788153/130363278-8b106ff0-c340-4666-8e5f-e3d09dd7e835.png)

If you used the previous project from #174 to try to collect drivetrain data, that might be the cause of these messed up graphs.

**Comment by willtoth** [comment]
Yeah this is for a non-drivetrain, so that is probably an issue. I'll try from source using gradle.

**Comment by Piphi5** [comment]
@willtoth have you gotten a chance to see if not using the drivetrain characterization fixed the issue?

**Comment by willtoth** [comment]
Trying to set up a better testing location, I may have some time today.

Either way, invalid input shouldn't crash the program.

**Comment by Piphi5** [comment]
Alright sounds good. 

That's just to make sure there isn't a larger issue at play with data analysis.

I'll try to reproduce the issue, because exceptions should be getting caught by the analyzer.

**Comment by Piphi5** [comment]
@willtoth does the program straight up crash for you or does it just throw an exception?

I'm currently unable to reproduce the issue with the data.

**Comment by willtoth** [comment]
Straight up crash. Even running from cmd doesn't show any output. I'll try again with the latest.

**Comment by Piphi5** [comment]
I managed to reproduce the issue with the release executable from the commit before the latest one on main. Perhaps the latest version does fix the issue.

**Comment by willtoth** [comment]
Just tried #176, this one still crashes.

However I did notice that the graph loads totally fine if I launch the application from Windows cmd.

**Comment by Piphi5** [comment]
Could you try running the executable from this [commit](https://github.com/wpilibsuite/sysid/runs/3411551646)?

I don't think #176 is rebased onto the latest commit yet.

**Comment by Piphi5** [comment]
@willtoth did you get a chance to try the latest version on main?

**Comment by Piphi5** [comment]
@willtoth PR #180 seems to fix the issue for me. Could you see if it also works on your end?

**Comment by willtoth** [comment]
Works for me, thanks!
