### ISSUE TITLE
Display version number in info dropdown

### ISSUE THREAD

**Issue by willtoth** [wpilibsuite/sysid#178]
Can you put the version info somewhere in the app? A git hash would also be useful.

**Comment by calcmogul** [comment]
The version number is included in the "Info > About" dropdown, but the version number the build generates is blank because we haven't pushed a tag yet. This'll be fixed once we push a tag for beta.

**Comment by prateekma** [comment]
Tag has been pushed now, so builds on main will have the correct version number.
