### ISSUE TITLE
Potential bug: distances traveled reporting as 0

### ISSUE THREAD

**Issue by benjaminJohnson2204** [wpilibsuite/sysid#193]
When I tried characterizing my robot's drivetrain using this tool, I had a problem where the reported distances traveled were 0 for both the left and the right sides. The robot's wheels were moving correctly, so the motors were being set correctly, but the encoders might be used wrong. Our drivetrain uses 4 TalonFX's, so I selected "Built-in" for encoders. I also tried changing the "Samples Per Average" from 1 to 5 and 10, and nothing helped. When I ran the robot's normal codebase and used the encoders to read how far the robot had traveled, the readings were correct, when the wheels moved so I know that the encoders work. Is this a bug with the sysID tool, or am I just using the tool incorrectly?

**Comment by Piphi5** [comment]
Looks like this may be a bug.

Can you send your `config.json` and if possible, try using the deployed program and seeing if the Network Table entries of `Left Position`, `Left Velocity`, etc. give a non-zero number.

**Comment by benjaminJohnson2204** [comment]
I'll have access to our robot and config file tomorrow, so I'll send the `config.json` and check the NetworkTable entries when possible!

I'm using the most recent version of SysID from the main branch, and I just downloaded SysID tonight.

**Comment by Piphi5** [comment]
Were you able to set the encoder ports from the GUI?

**Comment by benjaminJohnson2204** [comment]
Yes, I'll test it either tomorrow or the day after, and I'll let you know the results as soon as possible.

**Comment by benjaminJohnson2204** [comment]
@Piphi5 I tried running that build of SysID, and I still got distance traveled measurements of 0.

**Comment by Piphi5** [comment]
@benjaminJohnson2204 just to follow up, did the rest of the tool / calculated constants work well for you?

**Comment by benjaminJohnson2204** [comment]
Yes, the tool and calculated constants worked fine for us. Thanks again!
