### ISSUE TITLE
How to use this software

### ISSUE THREAD

**Issue by mendax1234** [wpilibsuite/sysid#199]
![image](https://user-images.githubusercontent.com/62934294/140351181-6e902127-97dc-4366-8b5b-f6b6ed0d4cdf.png)

After clicking , what should l click and where should l download it?

**Comment by calcmogul** [comment]
2021 and 2022 get installed to separate folders, so you can have them both installed at once.

**Comment by Piphi5** [comment]
https://github.com/wpilibsuite/sysid/actions/runs/1414619584

If you scroll to the bottom you can see executables for your operating system that you can download and run.

**Comment by calcmogul** [comment]
Interesting. The Linux binary is 207M, but all but 20M of that is symbols.

**Comment by mendax1234** [comment]
Thanks，l have installed this. However ，l still don't know how to use it. Is there any instructions?

**Comment by calcmogul** [comment]
These docs were updated for SysId: https://docs.wpilib.org/en/latest/docs/software/pathplanning/robot-characterization/

**Comment by mendax1234** [comment]
Thanks, l will dig into it.

**Comment by mendax1234** [comment]
Besides, it the feedforward different from the feedforward in CTRE? Otherwise , how can l convert feedforward in WPILIB to position control in CTRE's talonSRX

**Comment by calcmogul** [comment]
You'll have to read CTRE's docs for what units they use. Maybe it's here somewhere? https://docs.ctre-phoenix.com/en/stable/
