### ISSUE TITLE
Fractional decimal inputs

### ISSUE THREAD

**Issue by TateStaples** [wpilibsuite/sysid#206]
Just wondering if it would be possible to allow for fraction inputs (ie 1/20) into double fields. Not super important feature, but might be convenient for things like Gear ratios

**Comment by calcmogul** [comment]
I'm not really sure how to do this. `ImGui::InputDouble()` formats its input based on scanf-like format strings. For example, `"%.4f"` interprets the input as a floating-point number and truncates it to 4 decimal places.

Some cursory googling leads me to believe scanf() can't support this.
https://stackoverflow.com/questions/13574711/getting-a-fractional-number-with-scanf
https://stackoverflow.com/questions/15332212/reading-fractions-in-c

**Comment by calcmogul** [comment]
Maybe we could write our own input function like `InputFraction()` that validates input of the form `\d(/\d)?` where `\d` means `-?[0-9]+(\.[0-9]+)?`.

**Comment by Piphi5** [comment]
Is there an easy way to do regex in c++?

**Comment by calcmogul** [comment]
https://en.cppreference.com/w/cpp/regext

**Comment by Piphi5** [comment]
Does that mean we would have to use `InputText` and then have our own form of input validation?

**Comment by calcmogul** [comment]
Yea. If you follow the call tree far enough, you'll see all the functions just use InputText().

https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L3568

**Comment by Piphi5** [comment]
Should we have it so when they press enter on the GUI it gets converted into a decimal form or only when it gets saved to the JSON?

**Comment by calcmogul** [comment]
Either of those options means it'll load with a decimal number instead of the ratio. Maybe we could have two separate input boxes with a `:` between them for gear ratio.

**Comment by Piphi5** [comment]
True that'll probably be more intuitive
