### ISSUE TITLE
Write more unit tests for config loading

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/sysid#208]
https://github.com/wpilibsuite/sysid/pull/207 wasn't caught, and "Tachometer" is being loaded as "Built-in".

**Comment by Piphi5** [comment]
I think a lot of the error stems from the functions on the GUI end. Should we make a Utils file and unit test that?

**Comment by calcmogul** [comment]
Idk because I'm not sure what exactly needs to be unit tested. I haven't looked at the generator code before.
