### ISSUE TITLE
Add ADIS Gyro Support

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#240]
Currently not supported in generator setup

**Comment by sciencewhiz** [comment]
Has the libraries been updated for 2022? Last I checked they hadn't.

**Comment by Piphi5** [comment]
I don't think so, but currently, they're not even commented out or set up as a supported gyro anywhere in the code. So this issue mainly serves as a reminder so we don't forget about it.

**Comment by ngreen-gt** [comment]
I was just stopping by to ask about the ADIS16470, so glad to see it is in progress.  I did have to manually add it to our project until it is updated for 2022.

**Comment by Piphi5** [comment]
What do you mean by manually adding it?

**Comment by ngreen-gt** [comment]
Having to copy the source class into my project and then modifying the stuff that changed in 2022.  Here is the modified java class:  https://github.com/frc1108/2022NuggetBeta/blob/trunk/src/main/java/frc/robot/pantherlib/ADIS16470_IMU.java

**Comment by Piphi5** [comment]
@calcmogul is this something we should consider if ADIS isn't updated in time?

**Comment by Piphi5** [comment]
I'll consider adding it to the PR

**Comment by calcmogul** [comment]
This PR is relevant: https://github.com/wpilibsuite/allwpilib/pull/3777

**Comment by Piphi5** [comment]
I'll wait for that to merge
