### ISSUE TITLE
Help Dialog for Units Per Rotation

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/sysid#248]
I am documenting this better but it would help to have a little help be hoverable [here](https://github.com/wpilibsuite/frc-docs/issues/1542).  I think you would have to shrink all of the box sizes slightly but I can't think of anything that would come even close to using that large of a box.
![image](https://user-images.githubusercontent.com/15695521/146024867-bc40724e-f30c-46ae-98ff-fa74695c83a6.png)

**Comment by Piphi5** [comment]
Turns out there is a tooltip but because the box is so large, we don't see it
