### ISSUE TITLE
Remove Track Width Test from the Quasistatic Ramp Rate help text

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/sysid#249]
Track Width Test doesn't exist anymore.  I would just remove the mention.

**Comment by calcmogul** [comment]
Yes it does.

https://github.com/wpilibsuite/sysid/blob/main/sysid-application/src/main/native/cpp/analysis/AnalysisManager.cpp#L338-L348

**Comment by jasondaming** [comment]
Sorry what I should have said is that I don't know of anything user facing that is called track width any more.  I believe it is now called Drivetrain (angular)

**Comment by Piphi5** [comment]
Should we close this issue?

**Comment by calcmogul** [comment]
Depends on whether the quasistatic ramp rate value still references a trackwidth test.
