### ISSUE TITLE
Put time domain plots before voltage domain plots

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/sysid#257]
The time domain plots are more useful for determining goodness of fit in real scenarios than the voltage domain plots.

**Comment by Piphi5** [comment]
Currently, time steps vs time comes before voltage domain. Is this okay or should that be moved after the voltage domain fit?
![image](https://user-images.githubusercontent.com/29788153/147371215-656e8d1e-6132-4181-996c-2a02dbcc5c42.png)
