### ISSUE TITLE
Allow configuring of FeedbackControllerPreset for changing Measurement delays

### ISSUE THREAD

**Issue by modelmat** [wpilibsuite/sysid#259]
https://github.com/wpilibsuite/sysid/blob/main/sysid-application/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h

Currently the code only supports the default measurement delay.
If in the case where the user wants to change CTRE or REV's default settings, e.g. entirely disabling the moving average filter and/or decreasing the time period for calculating velocities, the presets do not reflect this and apparently cannot be changed within the GUI.

See also, #258

**Comment by Piphi5** [comment]
The measurement delay is configurable in the GUI (see the custom 10 second measurement delay)
![image](https://user-images.githubusercontent.com/29788153/147307420-5e854397-8d8e-4041-a3a3-fdc90a96da7c.png)
