### ISSUE TITLE
Refactor plot display code

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#269]
Currently, there is a lot of [hard coding](https://github.com/wpilibsuite/sysid/pull/268#pullrequestreview-839996036) that makes it difficult to customize the order of the plots if need be.

Also, the code could probably be cleaned up alot

**Comment by ngreen-gt** [comment]
I wanted to piggyback here that it would be nice if plots were also resettable.  The workspace>reset doesn't seem to affect the plots.

**Comment by Piphi5** [comment]
So like a button to reset the plot fittings?

**Comment by ngreen-gt** [comment]
How about if the analyzer reset button would also clear the diagnostic plots?  I'm not how compartmentalized the windows are but that would seem to make sense to me.  It is useful only that if you were to analyze a new file that you'd know that new diagnostic plots were generated for sure.

**Comment by calcmogul** [comment]
https://github.com/wpilibsuite/sysid/pull/270
