### ISSUE TITLE
Update CTRE Feedback Controller Presets

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#272]
Currently, the CTRE Presets are very unclear:
![image](https://user-images.githubusercontent.com/29788153/147523794-9dc3e54f-7b59-4c89-a277-d6e9c611f8ef.png)

**Comment by modelmat** [comment]
To be explicit, this was referring to the `CTRE (New)` preset, since CTRE's new units have not been added (and are stalled at the moment); making the `CTRE (Old)` preset the only one remaining.
