### ISSUE TITLE
SysID doesn't work if used on a freshly imaged roboRIO

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/sysid#278]
If you image a roboRIO and try to use SysID it will "complete" the deploy but there will be no robot code running and you can't connect to it.  I couldn't even see any logs to try to figure out what the issue was.

The easy fix to this is to deploy ANY frc program to the RIO and then use SysID again and it will work fine.

**Comment by calcmogul** [comment]
It's probably not deploying all the libraries it needs to. We should compare what libraries are deployed via GradleRIO vs SysId.

**Comment by ThadHouse** [comment]
I explicitly made it not include opencv. But that shouldn't affect things. I'll check when I get home.

**Comment by ThadHouse** [comment]
Ah, this is the "exec" bug

**Comment by ThadHouse** [comment]
https://github.com/wpilibsuite/GradleRIO/blob/main/src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java#L49
