### ISSUE TITLE
Add debug level setting

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/sysid#298]
Currently DEBUG messages do not show up in release builds, and there's no way to make them show up.  This would be very useful for debugging issues e.g. with deploying.

**Comment by calcmogul** [comment]
SysId uses wpiutil's Logger.h for logging. WPI_DEBUG() is compiled into a no-op if NDEBUG is defined. Should we be using a log level above debug?

**Comment by PeterJohnson** [comment]
Yes
