### ISSUE TITLE
Deploying should have a timeout

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/sysid#299]
Otherwise it can just hange at the "Discovering" step, necessitating a program restart to recover.

**Comment by calcmogul** [comment]
Does wpiutil's libuv support timeouts, and if so, how do I use them?

**Comment by PeterJohnson** [comment]
Most of the operations don't have direct timeouts, but you can start a timer in parallel and cancel things when the timer expires.

**Comment by calcmogul** [comment]
OBE by #518.
