### ISSUE TITLE
Fix Angular Drivetrain Unit Tests

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#307]
Currently the unit tests fail to test trackwidth:
```
double AngularDriveSim::GetPosition() const {
  return m_x(0) * m_trackwidth / 2;
}

double AngularDriveSim::GetVelocity() const {
  // The below comes from v = ω * r.
  return m_x(1) * m_trackwidth / 2;
}
```

It's also the reason behind #305 failing

**Comment by calcmogul** [comment]
Were the angular drive sim tests even testing anything new? They called CalculateFeedforwardGains() with the kDrivetrain argument just like the linear drivetrain tests. We also have a separate unit test for CalculateTrackWidth().
