### ISSUE TITLE
Assertion Failed: IMGUI Error and 

### ISSUE THREAD

**Issue by Ocean-Moist** [wpilibsuite/sysid#317]
Every time I try to open SysID I get this error:
![image](https://user-images.githubusercontent.com/26700549/150657132-e0c722ec-14bb-416f-b184-6ff35166a7f2.png)
When using the main branch and building from source I get a different error, this time after running any tests (i.e quasistatic forward) and pressing disable on the driver station.  It says cannot seek string iterator after end.

**Comment by PeterJohnson** [comment]
Delete C:\Users\<username>\AppData\Roaming\sysid*.json

**Comment by Ocean-Moist** [comment]
Ok, I can open it, but I still get the string iterator error. 

![image](https://user-images.githubusercontent.com/26700549/150657673-5f294a6a-2f96-4103-813f-de42f8805f54.png)

**Comment by PeterJohnson** [comment]
Is this on trying to analyze a particular file?  Posting the file would enable us to reproduce the issue to track down the root cause.

**Comment by Ocean-Moist** [comment]
While running the Quasistatic tests, this error occurs after I disable from the driver station.
here is my generator config:
https://pastebin.com/5kHqehc4
here is my logger data:
https://pastebin.com/Be1gfF0f

**Comment by Ocean-Moist** [comment]
Now after leaving it open I am getting another error. I just idled in Sys ID and this happened:
![image](https://user-images.githubusercontent.com/26700549/150658177-2c3c9208-ac41-40dd-acd2-f1cb0b745012.png)

**Comment by PeterJohnson** [comment]
I have no idea how it's tripping that assertion.

**Comment by nolanhergert** [comment]
> For this error, delete C:\Users<username>\AppData\Roaming\sysid*.json. The error you're seeing with tests is different. Does that error give you a source file / line number?

In my case, the sysid*.json files are defaulting to a different folder (C:\Users\Public\wpilib\2022\vscode). When I move the json files into a different folder, then I can launch the system identification tool again. Until I run into #319 and close normally. Then it shows up again!

Do you know why it's aborting? I would like to avoid having to do this each time / explain it to the students. The files are here: https://www.dropbox.com/s/ydn8b22x1r01odb/subfolder.zip?dl=0

**Comment by calcmogul** [comment]
The recent release (2022.3.1) fixes a lot of assertion failures.

**Comment by nolanhergert** [comment]
I no longer see this error! Now, just to get #319 working, but I suspect (due to the updated error message) that it's a problem with my setup. Thanks!
