### ISSUE TITLE
Error: Quasistatic test trimming removed all data 

### ISSUE THREAD

**Issue by Sentientnapkin** [wpilibsuite/sysid#319]
Here is the file I am trying to analyze: https://cdn.discordapp.com/attachments/900608549552529429/934642152472977428/sysid_data20220122-085328.json

**Comment by Piphi5** [comment]
When this error occurs, you can lower the Velocity threshold as [mentioned here](https://docs.wpilib.org/en/stable/docs/software/pathplanning/robot-characterization/viewing-diagnostics.html#improperly-set-motion-threshold).

The graphs load with a lowered threshold, however, judging by the fact that its a drivetrain test, and the units are technically impossible (1 rotation != .4710 rotations), I assume there is a major issue with how you are setting your units and units per rotation:
![image](https://user-images.githubusercontent.com/29788153/150663400-797cd64e-6a47-441c-9dff-13b026b5d42b.png)

![image](https://user-images.githubusercontent.com/29788153/150663333-c94b2ac4-3f69-4615-8a57-66d6c7e3dd49.png)

**Comment by Piphi5** [comment]
@Sentientnapkin can you send the generation config you used?

**Comment by Sentientnapkin** [comment]
So, I fixed the config (https://pastebin.com/nVSwmLnq), and it still tells me the same error. Here is the data we collected: https://gist.github.com/Sentientnapkin/82617e615f9ed8e846691af486f9c9a5

**Comment by Piphi5** [comment]
I think the gearing is wrong. It says that you have a 1:6 gear ratio, which you probably meant to have as a 6:1 since that's gearing the drivetrain down.

**Comment by Sentientnapkin** [comment]
> I think the gearing is wrong. It says that you have a 1:6 gear ratio, which you probably meant to have as a 6:1 since that's gearing the drivetrain down.

for every six turns of the motor, the wheel turns once. but we are using REV throubore encoders that are directly on the out put shaft. so when the wheel turns once, the encoder would have 8192 counts, or one revolution, while the motor would have spun 6 times. what are the appropriate settings in this scenario

**Comment by Piphi5** [comment]
The gearing is between the encoder shaft and output shaft. If the encoder is on the output shaft, the gearing is 1:1

**Comment by Piphi5** [comment]
Also judging by these plots of your data, you don't seem to move during the slow-forward or fast-forward tests:
![image](https://user-images.githubusercontent.com/29788153/150701924-4d385d6f-a780-4d9e-a11a-bd2003f633a2.png)
![image](https://user-images.githubusercontent.com/29788153/150701936-7fd12bdc-b379-4771-880c-63650311bb86.png)

It seems like the robot doesn't send forward commands to the motors:
![image](https://user-images.githubusercontent.com/29788153/150701980-2e84ca08-29de-45bb-a710-e003ffd2cc79.png)

**Comment by Sentientnapkin** [comment]
well the robot does actually move, does this mean I have encoder ports wrong?

**Comment by Sentientnapkin** [comment]
I do not understand why it worked for the other tests if I got encoder ports wrong. During slow forward and Dynamic forward it does move.

**Comment by Piphi5** [comment]
Its most likely not a port issue or the program would've crashed.

**Comment by Piphi5** [comment]
It seems like the tests are very short-lived. How long do you leave the slow forward and dynamic forward running for?

**Comment by Sentientnapkin** [comment]
around 30 feet.

**Comment by Piphi5** [comment]
What does sysid report measuring in the telemetry window?

**Comment by Sentientnapkin** [comment]
received data with size 3587 for the slow-forward test in 17 seconds.

**Comment by Piphi5** [comment]
This initial popup also changes after the test to say how far the mechanism moved:
![image](https://user-images.githubusercontent.com/29788153/150702575-77556d8b-8e1a-4554-afc5-9accf336d021.png)

What distance does it read after you hit disabled?

**Comment by Piphi5** [comment]
> received data with size 3587 for the slow-forward test in 17 seconds.

Is this with respect to the bad data you sent or is this a new test?

**Comment by Sentientnapkin** [comment]
Like 1.98

> > received data with size 3587 for the slow-forward test in 17 seconds.
> 
> Is this with respect to the bad data you sent or is this a new test?

bad data. and it said 1.98.

**Comment by Piphi5** [comment]
So SysId noticed that the robot moved 1.98 meters but then saved bad data?

**Comment by Sentientnapkin** [comment]
I redid it and got no error. But my data is off by a factor of like 3. here is my data: https://gist.github.com/Sentientnapkin/1358fdd3799d900455c4bf1a2d78fc1d. It definitely goes faster than .7 m/s during the dynamic tests.

**Comment by Piphi5** [comment]
What config are you using now?

**Comment by Sentientnapkin** [comment]
{
  "counts per rotation": 256.0,
  "encoder type": "roboRIO quadrature",
  "encoding": true,
  "gearing denominator": 28.0,
  "gearing numerator": 3.0,
  "gyro": "NavX",
  "gyro ctor": "SerialPort.kMXP",
  "is drivetrain": true,
  "motor controllers": [
    "VictorSPX",
    "VictorSPX"
  ],
  "number of samples per average": 5,
  "primary encoder inverted": true,
  "primary encoder ports": [
    0,
    1
  ],
  "primary motor ports": [
    0,
    1
  ],
  "primary motors inverted": [
    false,
    false
  ],
  "secondary encoder inverted": false,
  "secondary encoder ports": [
    2,
    3
  ],
  "secondary motor ports": [
    2,
    3
  ],
  "secondary motors inverted": [
    true,
    true
  ],
  "velocity measurement period": 100
}

**Comment by Piphi5** [comment]
Why are your counts per rotation 256 now? And again the gearing is a little concerning. The gearing numerator should be bigger than the denominator.

**Comment by Sentientnapkin** [comment]
The gearing is incorrect, I accidentally uploaded the wrong file, it's 28:3, everything else is right. We are using a different robot to test if it works and the CPR is 256 on this one.

**Comment by Piphi5** [comment]
so was the gearing correct when you tested the robot?
