### ISSUE TITLE
Sysid breaking when using drivetrain (angular) parameter

### ISSUE THREAD

**Issue by ctrl-alt-delete101** [wpilibsuite/sysid#324]
I tried characterizing our team's practice robot to get angular gains from SysID. I was able to run all the tests properly however when trying to read the data I got an exception error message: "Quasistatic test trimming removed all data". 
![image](https://user-images.githubusercontent.com/57509291/150904595-24ac5f2f-e3ae-4aa4-a295-04dfaadeacb5.png)

After getting that error message I exited sysid and tried to reload it but I was given another error
![image](https://user-images.githubusercontent.com/57509291/150904634-25dc3776-4002-4797-a94b-7066e0bf0136.png)

Json file that I used
https://gist.github.com/ctrl-alt-delete101/edcb94982856901b68584a63212e3aab

**Comment by Piphi5** [comment]
![image](https://user-images.githubusercontent.com/29788153/150913511-1d7905a3-b738-4321-b626-2800566f5fa9.png)
![image](https://user-images.githubusercontent.com/29788153/150913534-17d8bd89-744c-418b-925e-2e09c9c97cfd.png)

From this script, it seems like the robot didn't move a whole lot. Was that the case?

**Comment by ctrl-alt-delete101** [comment]
Yea the robot didn't rotate for that long, however I did the same with a longer trial and the same thing occured.

**Comment by ctrl-alt-delete101** [comment]
> ![image](https://user-images.githubusercontent.com/29788153/150913511-1d7905a3-b738-4321-b626-2800566f5fa9.png) ![image](https://user-images.githubusercontent.com/29788153/150913534-17d8bd89-744c-418b-925e-2e09c9c97cfd.png)
> 
> From this script, it seems like the robot didn't move a whole lot. Was that the case?

Yea the robot didn't rotate for that long, however I did the same with a longer trial and the same thing occured.

**Comment by ctrl-alt-delete101** [comment]
Yea the robot didn't rotate for that long, however I did the same with a longer trial and the same thing occured.

**Comment by Piphi5** [comment]
Can you send data for the longer trial?

**Comment by ctrl-alt-delete101** [comment]
I don't have that data on me right now. Although I don't know if its useful but I have data from a normal drivetrain parameter.

**Comment by Piphi5** [comment]
Do you know what gearing you used?

**Comment by ctrl-alt-delete101** [comment]
I believe its 16:1

**Comment by Piphi5** [comment]
Did the reported measured values make sense to you?

**Comment by ctrl-alt-delete101** [comment]
Everything seemed relatively normal, however the acceleration graphs looked weird. I tried to use the values on our mecanum drive but the wheels kept going back and forth so I believe I have to correctly tune the position controllers. I'll also link the json file that I used.

r-squared: 0.99995
Sim rsme: 0.12369

https://gist.github.com/ctrl-alt-delete101/146fe418d9ad6a410a725ad5d90d0a05

**Comment by Piphi5** [comment]
FYI, the sysid on main is getting a better fit. Can we consider this issue closed?
![image](https://user-images.githubusercontent.com/29788153/151250777-ffb0eacf-4dfa-4d60-ab23-0c3ea106cc2d.png)

**Comment by ctrl-alt-delete101** [comment]
Yep, seems good.
