### ISSUE TITLE
Editing Projects with Custom Code

### ISSUE THREAD

**Issue by LudumDareDevelopment** [wpilibsuite/sysid#326]
Is it possible to edit the code that is deployed to the robot from sysID like frc-characterization could? I plan on characterizing a swerve drive, and it would be nice if I could command my steering motors to an angle of 0 constantly, but I currently cannot set this up with sysID.

**Comment by Daltz333** [comment]
Unfortunately not. This is a design decision. Editing the custom project has led to more issues than benefits.

**Comment by calcmogul** [comment]
It comes down to not being able to trust the average user to not mess things up.

**Comment by LudumDareDevelopment** [comment]
Interesting. Thank you for the help!

**Comment by LudumDareDevelopment** [comment]
Is frc-characterization forwards compatible with WPILib 2022? I would imagine it would still work if the Network Tables protocol did not change

**Comment by Piphi5** [comment]
No the network tables protocol is different

**Comment by Piphi5** [comment]
If you know cpp you can use the files in sysid-library to take advantage of the new protocol

**Comment by calcmogul** [comment]
However, if you record data with frc-characterization, it'll be transparently converted to the sysid format if it's loaded into sysid.

**Comment by LudumDareDevelopment** [comment]
Would recording data with frc-characterization be possible if the characterization project version is set to WPILib 2022?

**Comment by calcmogul** [comment]
I don't believe so.
