### ISSUE TITLE
Pigeon Yaw units are double-converted from radians to degrees

### ISSUE THREAD

**Issue by jlmcmchl** [wpilibsuite/sysid#331]
Tested w/ version 2022.1.1 - checking commits between that release and master I've observed that the AngularDriveSim analysis has been removed, but no changes have been made to the way data is acquired from the pigeon. Due to #324 I'm unable to determine if this is an issue strictly in displaying the value or something else. 

Nevertheless - the CTRE pigeon returns a value in degrees, and that is displayed back to the user as if it had been radians, and converted once more to degrees.
![sysid_1](https://user-images.githubusercontent.com/1332080/151106362-d819b785-8348-4be1-9cc7-8d8693686b46.png)

As you can see, the robot turned 21804 degrees, which is 180 / pi * 380. In reality, the robot performed a little over 1 full rotation.

**Comment by Piphi5** [comment]
That is definitely an issue that hasn't been fixed yet.

**Comment by Piphi5** [comment]
Just confirmed pigeon gyro positional units are returned as degrees.

**Comment by Piphi5** [comment]
@jlmcmchl Can you see if the executables from this [PR fixes ](https://github.com/wpilibsuite/sysid/actions/runs/1753081476) the issue?

**Comment by jlmcmchl** [comment]
I'm back in the shop friday, so I'll update you after testing at that time.

Thanks for getting back so quickly!
