### ISSUE TITLE
Crash on windows 10 64-bit

### ISSUE THREAD

**Issue by danielbrownmsm** [wpilibsuite/sysid#340]
Hey there, team 2718 here.
After running the tests to generate data for our drivetrain (although the tests were over a fairly short distance and time), we loaded it into the analyzer to analyze it. We then got a message that said "Quasistatic test trimming removed all data." So we were going to go and redo the tests to get better data, but for some reason one of the programmers decided to click the "dataset" drop-down box and select "forward," which causes the tool to crash. Upon reopening we got the assertion errors screenshotted below. The tool is now broken and will not work again, even after restarting the computer. The data set that caused this is also attached below. The tool does not break, however, after being installed directly from github instead of the FRC-2022 WPILib installer. It still crashes whenever "forward" is selected.

![Capture](https://user-images.githubusercontent.com/56051347/151471230-6e16f500-349c-47a3-b98f-ecc639c45d03.PNG)
![Capture1](https://user-images.githubusercontent.com/56051347/151471232-b1b77f47-d122-4d3d-9e17-a61509d86bac.PNG)
[sysid_data20220127-190536.zip](https://github.com/wpilibsuite/sysid/files/7955020/sysid_data20220127-190536.zip)

**Comment by Piphi5** [comment]
The reason for the quasistatic trimming is either a units issue or an improperly run test. From the JSON it says the robot goes 1 meter per rotation, which is highly unlikely. The raw data graphs show that one of the quasistatic tests barely moved:
![image](https://user-images.githubusercontent.com/29788153/151500224-861c76de-c9de-4366-b2f4-ee88212ab9d1.png)
