### ISSUE TITLE
Remove dataset combo box

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#341]
Users are more likely to get inaccurate fits from choosing different subsets of their data (e.g. forward, backward) and as a result, the dataset combo box in the Analyzer should be removed in addition to any analysis code made to store these different subsets.

For reference this is the combo box:
![image](https://user-images.githubusercontent.com/29788153/151499950-b0175b74-eaea-41ec-8779-316ca11738ab.png)

**Comment by camearle20** [comment]
This feature was extremely useful to generate separate left and right characterization values, something which is critical to getting a robot to drive straight in open loop.  I'm not sure why this was just entirely removed?  Could at least the left/right combined options be added back?
