### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by aidan-mundy** [wpilibsuite/sysid#356]
WPILib 2022.3.1
Windows 10

When I start sysID (just the program, not the characterization), it immediately locks up, and then consumes all of the ram on my computer (32ish gigs). This doesnt seem normal to say the least. Any help?

**Comment by PeterJohnson** [comment]
Try deleting c:/users/<username>/AppData/Roaming/sysid*.json.  Make a copy first so you can upload them here if that fixes it.

**Comment by calcmogul** [comment]
Unable to reproduce the issue.
