### ISSUE TITLE
Add back ability to generate left/right combined drivetrain feedforward values

### ISSUE THREAD

**Issue by camearle20** [wpilibsuite/sysid#361]
#341 removed the combo box which selected the type of analysis to do on a drivetrain characterization dataset.  While I agree that it makes sense to remove the forward/backward confusion, I still think there is value in being able to obtain a separate left and right dataset.  I think the default value of the box could remain as "combined" but there is real value in being able to produce separate left and right (combined) values.

**Comment by calcmogul** [comment]
> I still think there is value in being able to obtain a separate left and right dataset.

Why?

**Comment by camearle20** [comment]
Mainly for a drivetrain with less than ideal construction.  I have found it very helpful to get at least separate Ks values for each side of the drive to account for those differences.  We typically run a separate model for the left and right sides of the drive.

FWIW, I'm also seeing slightly better R2 velocity values using left combined/right combined on the previous release than using the whole combined mode.

**Comment by calcmogul** [comment]
That PR removed forward vs back split. SysId never supported left vs right.

**Comment by camearle20** [comment]
<img width="211" alt="image" src="https://user-images.githubusercontent.com/2140370/152722549-14b97be0-e222-4818-b1d9-2dfe5401d860.png">

The options were at least in the dropdown, and clicking them gave different outputs.  I'm not sure how/if they were actually implemented though
