### ISSUE TITLE
Improve Telemetry Manager to avoid data mismatch issues

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#363]
Implementing features like Sequence numbers and better data polling can fix the issue where users sometimes have mismatched test data from sysid grabbing outdated Telemetry data.

**Comment by Oblarg** [comment]
A flat data structure with a "test name" field makes the most sense to me.

**Comment by Piphi5** [comment]
Yeah that seems like a more reasonable structure of doing things

**Comment by Piphi5** [comment]
A major concern is that there right now there isn't a great way of reproducing the issue consistently. And we can't figure out if this issue is solved without that

**Comment by Piphi5** [comment]
Due to potential conflicts between server and client-side handling of data we should use acknowledgment numbers to make sure data has been received and stored before clearing it.

I think the best and most testable/robust approach would be a combination of including the test on the robot telemetry output and implementing the acknowledgment numbers, resolving both test mismatches and NT issues.
