### ISSUE TITLE
Add Romi generation preset

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/sysid#37]
frc-char requires special setup for characterizing a Romi. While constants are mostly plug-n-play for users of Romi, it's a great learning platform, and we should add a preset for Romi.

**Comment by Piphi5** [comment]
Would this just be for the Romi drivetrain?

**Comment by Daltz333** [comment]
Yes.

**Comment by Piphi5** [comment]
Are the ports, epr, etc. all fixed? Or should they be able to change that in the GUI?

**Comment by Daltz333** [comment]
It's all fixed. The Romi project is simulation with the websockets enabled and pointed toward 10.0.0.2

**Comment by Piphi5** [comment]
Alright, I think we're going to add an option in #24 that'll generate a fixed config file for it.

**Comment by Piphi5** [comment]
@Daltz333 Would you be able to test #24 on your Romi once it's finalized?

**Comment by Daltz333** [comment]
Yes

**Comment by Piphi5** [comment]
@Daltz333 Could you test PR #24 on a Romi?

You would probably need to do the following procedure:
1. Pull the branch
2. Run the GUI
3. Use the `Romi` preset on the generator and save the config
4. Deploy the Drivetrain project (which will be located in the `base_projects/drivetrain` folder)
5. Run telemetry and analysis and see if the numbers roughly match up with the old tool.

**Comment by Daltz333** [comment]
Can you send me a compiled executable?

**Comment by Piphi5** [comment]
Actually, I'll have to send everything after #38 is merged. 

You would probably still need to pull the files as of right now just because we haven't fully figured out how we're going to deploy the project so the GUI saves the config into a hardcoded subdirectory in the repo.

**Comment by prateekma** [comment]
I'll try to get 38 merged by Thursday night

**Comment by Piphi5** [comment]
Alright, no rush. I still have some changes to make as well.
