### ISSUE TITLE
[Feature Request] Limit Switch Support To Sysid

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/sysid#400]
When characterizing high inertia and powerful mechanisms (elevators and arms mainly), teams want to be very careful that their mechanisms do not break or get over driven. On a normal robot, this is done with limit switches. By being able to just tell sysid what DIO ports my limit switches were on and if they are normally true/false, it would be a lot easier to safely characterize my mechanisms. This feature could also be used in lieu of the disable button on certain mechanism.

**Comment by Piphi5** [comment]
Would this be a single limit switch?

**Comment by mdurrani808** [comment]
Two limit switches would make the most sense (mechanism up/down) but I assume most teams will just use 1.
And if soft limits could be integrated, that would be probably be best, accessibility wise.

**Comment by calcmogul** [comment]
OBE by #518.
