### ISSUE TITLE
sysid deploy problem. We are using vmx pi

### ISSUE THREAD

**Issue by sipmine** [wpilibsuite/sysid#403]
When using the characteristics of the robot, I encountered the following problem:

![Uploading v{49eeae9} (3d75e911-5d83-49b9-a501-3594768a970c id=0x7f0a0194 tag=CreateIssueFragment) …]()

I don’t understand why this happens, since the status of the network tables is “NT connect” in the logger, but if you run one of the tests and activate the offline mode, then nothing happens, I specified all the engine connections, and yes, when this error occurs, I I can connect to the controller at the same addresses via SSH

**Comment by calcmogul** [comment]
SysId only supports the roboRIO. The robot binary it deploys doesn't work on the VMX-pi.
