### ISSUE TITLE
Refactor NT logging in integration_test_project into SysIdLogger classes

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/sysid#41]
Even if we do code generation, the abstraction there will be helpful in codegenned projects as well as teams who decide to gather characterization data in situ anyway.

**Comment by prateekma** [comment]
We should also discuss whether we want to add these logger classes to WPILib so that teams can use it from their regular robot code.

**Comment by Piphi5** [comment]
Should we have it as an interface where they just implement methods to collect data and set motor speed or should it be an abstract class that also handles the Network Tables reading and string publishing?

**Comment by calcmogul** [comment]
It should handle the reading and publishing stuff that's in https://github.com/wpilibsuite/sysid/blob/main/integration_test_project/src/main/cpp/Robot.cpp. SimpleMotor would have the following functions:

```cpp
class SimpleMotorLogger {
  SimpleMotorLogger() {
    // Disable LiveWindow telemetry
    // Create necessary NT entries with SmartDashboard put functions
  }

  // Called by user in AutonomousPeriodic() or TestPeriodic()
  void Log(units::volt_t batteryVoltage, units::volt_t motorVoltage, double velocity) {
    // Get timestamp here with frc2::Timer::GetFPGATimestamp()
    // Fill in data array and log it
  }

  // Called by user in DisabledInit()
  void SendData() {
    // Sends the giant data buffer over NT
  }
};
```
Their contents would roughly correspond to what's in AutonomousPeriodic() and DisabledInit() in the previous Robot.cpp.

**Comment by Piphi5** [comment]
Should any changes be made to [these logging classes](https://github.com/Piphi5/sysid/tree/generation/integration_test_project/src/main/include/logging)?

**Comment by calcmogul** [comment]
The APIs look good, but the implementations look incomplete.

**Comment by Piphi5** [comment]
Implementations as in integrating it into the respective robot projects?

**Comment by calcmogul** [comment]
No. The classes themselves don't appear to be finished.

**Comment by calcmogul** [comment]
Oh, some stuff was hiding in the base class.

**Comment by calcmogul** [comment]
I have some other comments for cleanup, but I'll save those for a PR.
