### ISSUE TITLE
Rewrite frc-docs articles that reference frc-characterization to use sysid

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/sysid#42]

**Comment by Piphi5** [comment]
Is there a branch we can start working on docs on?

**Comment by prateekma** [comment]
Not yet. I will work on it a little tonight.

**Comment by prateekma** [comment]
https://github.com/wpilibsuite/frc-docs/pull/1280

**Comment by Piphi5** [comment]
This has been resolved on [frc-docs](https://github.com/wpilibsuite/frc-docs/pull/1280).
