### ISSUE TITLE
Using sysid for two separate deployments always fails w/ SysIdWrongMechanism=true

### ISSUE THREAD

**Issue by jlmcmchl** [wpilibsuite/sysid#469]
Between uses of sysid, I've noticed that I always need to restart sysid in order to control new deployed sysid projects.

Steps to recreate:

Setup:
1. Configure project w/ any project type, motors, encoders, gyro
2. Deploy project
3.  (Optional) restart sysid

Tasks to recreate:
1. Run a test w/ the correct project parameters. Observe that motors move.
2. Re-deploy the same project
3. Run a test without changing anything in the `Logger` window. Observe that motors don't move, and upon disable the application reports "ERROR: The robot indicated that you are using the wrong project for characterizing your mechanism."

If sysid is restarted, then a previously-deployed robot project can be controlled without issue.

**Comment by bruingineer** [comment]
I've run into the same behavior
