### ISSUE TITLE
Integration tests only uses smartdashboard to change mechanism

### ISSUE THREAD

**Issue by KyleQ1** [wpilibsuite/sysid#47]
When running the integration tests it seemed to only change mechanism when we changed the value from Drivetrain on SmartDashboard instead of using what's in sysid.

**Comment by calcmogul** [comment]
You mean the integration test project, right?

**Comment by prateekma** [comment]
It was really intended as an internal thing but we can publish the mechanism to NT in TelemetryManager as well

**Comment by calcmogul** [comment]
We mainly did this because frc-char was unreliable and we needed working telemetry. Robot-side telemetry logging classes would mean we no longer have to use the integration test project.

**Comment by Piphi5** [comment]
We could probably have the Telemetry and Logging classes finalized by maybe next week? Then you could probably paste the files into your code.

**Comment by calcmogul** [comment]
We got good results with this approach and don't need to characterize anything else atm, so no rush.
