### ISSUE TITLE
SysID not working with Pigeon 2 gyro

### ISSUE THREAD

**Issue by RichSims686** [wpilibsuite/sysid#473]
**Describe the bug**
SysID is reporting a gyro delta angle of 0 degrees even though the robot is obviously turning during SysID path.  CAN ID of Pigeon 2 gyro is configured correctly.  Phoenix Tuner and team robot code can read gyro on this CAN ID.

**To Reproduce**
1. Configure SysID with Pigeon 2 as gyro on correct CAN ID port
2. Run SysID linear quasi-static or dynamic test.  Observe robot veering off to the left.  :)
3. SysID reports 'gyro angle delta was 0 degrees'

**Expected behavior**
Expect non-zero gyro readings.

**Screenshots**
![image](https://user-images.githubusercontent.com/90807828/215275139-aa63172b-667f-4a01-8713-69b91a26eb6b.png)
![image](https://user-images.githubusercontent.com/90807828/215275148-c78c132b-2963-47bb-808e-a6cc0b310c40.png)
![image](https://user-images.githubusercontent.com/90807828/215275156-725ba629-70fd-430f-99d8-5dbcd847894a.png)

**Desktop (please complete the following information):**
 - WPILib Version: 2023.2.1  (also tested updated vendordeps at https://github.com/wpilibsuite/sysid/actions/runs/4028733731)
 - OS: Windows 10
 - Java version 17.0.5
 Pigeon 2 Firmware: 26.6.2.2 (latest as of today, released Jan 13)

**Additional context**
Response in CD thread indicates multiple teams are seeing this: https://www.chiefdelphi.com/t/sysid-not-working-with-pigeons/424879

**Comment by hdsbbrooks** [comment]
We were having this issue and by running the canivore build from PR455 (https://github.com/wpilibsuite/sysid/pull/455) we were able to get values from the pigeon2.  (6xfalcon WCD, 2x cancoder, 1x pigeon2, phoenix v5).

**Comment by RichSims686** [comment]
We were able to get the Pigeon2 gyro working with SysID with the build below, verifying what was [suggested in this thread](https://www.chiefdelphi.com/t/sysid-not-working-with-pigeons/424879/5?u=richard_sims)

[https://github.com/wpilibsuite/sysid/actions/runs/3978139611](https://github.com/wpilibsuite/sysid/actions/runs/3978139611)

**Comment by calcmogul** [comment]
Fixed by #455.
