### ISSUE TITLE
SysId robot program exits with "Hall sensor measurement period must be in the range of [8, 64]"

### ISSUE THREAD

**Issue by yotam201410** [wpilibsuite/sysid#479]
we have been trying to use SYSID in order to get kp,ki,kd,ks,kv, and ka constants of our drivetrain with SYSID but we jeep getting 
```﻿﻿﻿﻿﻿﻿
Project failed: Hall sensore measurement period must be in the range of [8, 64] ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix-diagnostics] Server shutdown cleanly. (dur:0) ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix] Library shutdown cleanly ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ pure virtual method called ﻿
﻿﻿﻿﻿﻿﻿ terminate called without an active exception
```
last year and this year the robot didnt move (the code got deployed and run) but last year we've managed to find a workaround using
[SysidJavaLogger](https://github.com/RegisJesuitRobotics/SysIdJavaLogger) for this year Sysid says that the data doesn't get to the NT Entry I checked it in the Sysid code and the entry hasn't changed.
if anyone has a solution it would be very appreciated things I have tried include:
downloading a new wpilib suite
downloading the latest build of Sysid
compiling Sysid
updating spark max to the latest image
the robot it selfs works with the regular code and so with the Sysid Code (V1.2) (there are no errors reported) but when enabling the autonomous the SparkMax does not show any voltage going to the motors. here are the IDs of the motors:
10 left forward
11 left Backward
12 right forward 
13 right backward
[https://www.chiefdelphi.com/uploads/default/original/3X/f/b/fb2df2cdafea3aba86e27954d39b45dd6e581449.jpeg](here is the image from V1.2)
I have played with the motor's ID in which slot are they but it hasn't worked.

**Comment by sciencewhiz** [comment]
Fixed by #478

**Comment by sciencewhiz** [comment]
What was the version you tested it on? There's been two releases in the last 2 days, so I want to make sure you tested the right version. The current latest is 2023.3.2.

**Comment by yotam201410** [comment]
yes, i did

**Comment by Alextopher** [comment]
v2023.3.2 we see the same error

**Comment by calcmogul** [comment]
Could you try this build from #481?
https://github.com/wpilibsuite/sysid/actions/runs/4105458814

**Comment by yotam201410** [comment]
ill try it tomorrow when ill be at the workshop

**Comment by Lann4daze** [comment]
We just tried the latest build on wpilib 2023.3.2, and we're still getting that hall sensore measurement error, and occasionally an `Error in '/home/lvuser/frcUserProgram': free(): invalid next size (fast): 0x00ce4c88`

**Comment by yotam201410** [comment]
> Could you try this build from #481? We have no hardware to test on. https://github.com/wpilibsuite/sysid/actions/runs/4105458814

still getting the same error,
here is the config [file](https://easyupload.io/allvfs)

**Comment by calcmogul** [comment]
I think it was missing initialization code. Try the build from https://github.com/wpilibsuite/sysid/actions/runs/4116398469 when it's complete.

**Comment by yotam201410** [comment]
> I think it was missing initialization code. Try the build from https://github.com/wpilibsuite/sysid/actions/runs/4116398469 when it's complete.

it fixed the issue thank you very much
