### ISSUE TITLE
CANivore error when loading old config

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/sysid#482]
Configs created before v2023.3.2 give an error when loading.
![image](https://user-images.githubusercontent.com/1993518/217045350-e941b13c-553a-4f2f-88b4-b51db9977608.png)

Steps to reproduce
1) Create a config in a previous 2023 version of SysId
2) Upgrade SysId
3) Attempt to load the config

**Comment by agasser** [comment]
> CANivore support caused breaking changes in the project generator JSON.

It looks that way. It probably should default to "rio".

**Comment by calcmogul** [comment]
Could you upload an old JSON for testing?

**Comment by agasser** [comment]
[shooter-config.json.txt](https://github.com/wpilibsuite/sysid/files/10667722/shooter-config.json.txt)

**Comment by calcmogul** [comment]
OBE by #518.
