### ISSUE TITLE
Sysid Values change when switching to and from Drivetrain sides

### ISSUE THREAD

**Issue by Danial-Sy** [wpilibsuite/sysid#484]
My team and I recently ran a sysid test and retrieved our values. We observed an issue, a difference between two values when switching to and from them. To clarify, the values for a given side change. That is, for example, going from “combined” to “left” gives one set of values, and then clicking on “left” on the dropdown again shows a different set, even though those values should not change. The images attached below show the problem with all sides.

![2ndImageSys](https://user-images.githubusercontent.com/122944980/217078278-e06c6562-c5fb-4c19-92d4-83396414f196.png)
![beforethechange](https://user-images.githubusercontent.com/122944980/217078281-2a26b94c-2c13-4d53-8834-afe410f68aa2.png)
![1stCombinedPIDValueREALEDITIIONG](https://user-images.githubusercontent.com/122944980/217083255-dcf37cd3-75ac-40d8-8f11-5482ac2b7f13.png)
![2ndCombinedPIDValues](https://user-images.githubusercontent.com/122944980/217083259-1f32261b-e73e-41db-ae2f-ff0e5cb8e9c9.png)
![1stRightPIDAfterSwitchFromCombined](https://user-images.githubusercontent.com/122944980/217083256-19391828-11fe-4189-bb0b-bd1146b66656.png)
![3rdSysIDValue](https://user-images.githubusercontent.com/122944980/217083262-542da907-72c2-4747-bd94-6e92dfb0d471.png)

**Comment by calcmogul** [comment]
The gains actually will change depending on which data you give it. "Combined" is usually the best one to use.

**Comment by Shiv-Shah** [comment]
> This doesn't seem like a bug. The gains will vary depending on which datset you give it, and they don't appear to vary much in the screenshots. "Combined" is usually the best option to use because it uses all data available.

To rephrase what is happening here. Daniel pressed on combined once. Then Changed to Left, and then Left again. When changing lefts twice this error occurs. This shouldn't be a dataset issue as the dataset is the same.

**Comment by calcmogul** [comment]
Could you upload your analysis JSON so the issue can be reproduced?

**Comment by Shiv-Shah** [comment]
[SysId.zip](https://github.com/wpilibsuite/sysid/files/10670920/SysId.zip)

That zip file contains the JSON

**Comment by calcmogul** [comment]
Looks like the numbers in the analysis pane aren't updating until the dropdown item is selected twice.

**Comment by Shiv-Shah** [comment]
Which values do we use for this senario.

**Comment by calcmogul** [comment]
Use combined.

**Comment by Shiv-Shah** [comment]
which combined? And how is that different from left and right?

**Comment by calcmogul** [comment]
The dataset dropdown you've been using in the analyzer pane has "Left", "Right", and "Combined" options for drivetrain data. Left uses the left side's data, Right uses the right side's data, and Combined uses both.

**Comment by Shiv-Shah** [comment]
However if you look at the screen shots above and use our dataset. What you'll see are different values for when you press combined right right combined. Hence combined has 2 values. Which one do we use?

**Comment by calcmogul** [comment]
Again, you have to press the button twice because it's doesn't switch after pressing just once.

**Comment by Shiv-Shah** [comment]
ahh didn't see the part for the button twice thank you for the info. Any idea as to why this issue occured?

**Comment by calcmogul** [comment]
From my earlier post:

> Perhaps it's because the analysis code occurs before the dropdown's polling code.

**Comment by Shiv-Shah** [comment]
got it thanks!
