### ISSUE TITLE
CANivore name does not load from config

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/sysid#486]
When using a CANivore and the _Motor CANivore Name_ field is populated with a value other than "rio", the stored value does not repopulate when the config is loaded from a file.

Steps to reproduce:
1) Create a drivetrain project
2) Add a set of TalonFX motors
3) Set the CAN bus name to "swerve"
4) Save
5) Close SysID
6) Open SysID and load the config

The CAN bus name will be "rio" instead of the expected "swerve".

Here is an example config:
[config.json.txt](https://github.com/wpilibsuite/sysid/files/10807004/config.json.txt)

Frustratingly, this is related to #482 where a CANivore name is required in the config file, even though it doesn't load.

**Comment by calcmogul** [comment]
OBE by #518.
