### ISSUE TITLE
Lots on NaN values in analysis

### ISSUE THREAD

**Issue by DAflamingFOX** [wpilibsuite/sysid#504]
![image](https://user-images.githubusercontent.com/59402059/228378469-b6235fde-6cad-4a85-bbd7-e982b1416b39.png)
https://drive.google.com/drive/folders/15xvh2yAA24H4YBaGJ5t2FkWtN82asUdD?usp=share_link

**Comment by calcmogul** [comment]
[config.json.txt](https://github.com/wpilibsuite/sysid/files/11094636/config.json.txt)
[sysid_data20230328-164517.json.txt](https://github.com/wpilibsuite/sysid/files/11094637/sysid_data20230328-164517.json.txt)

**Comment by calcmogul** [comment]
The arm analysis says it used meters, for some reason. If I manually edit the JSON to use "Radians" instead, the analysis doesn't give NaN anymore.

**Comment by calcmogul** [comment]
OBE by #518. The units are determined by the project JSON, and the project generator was removed.
