### ISSUE TITLE
Follow not set on SparkMAX Drivetrain

### ISSUE THREAD

**Issue by mikejdavey1** [wpilibsuite/sysid#506]
While performing SysID on our Tank Drive with 2 NEOs per side via SparkMAX CAN, we  would hear clicking in the gearbox that we didn't have while driving normally.  Upon review with the Hardware client we saw that follow as not being set for one of the two motors.  We had to deploy code, then connect via USB to the Spark's to configure Follow in the advance settings to get valid SysID data.

Everytime we rebooted the RIO or Restarted the code we had to reset the configuration in the SPARK MAXs.

**Comment by calcmogul** [comment]
OBE by #518.
