### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by Rarras5144** [wpilibsuite/sysid#507]
So looking to see if i can get some help here I am trying to learn command based and more advanced programming on our 2023 robot and i need to use sysid to do so but sysid when deployed states no robot code on DS and when looking in logs has an overrun warning and a symbol lookup error
(any help appreciated)
![logfile](https://user-images.githubusercontent.com/124696826/231193326-b20ce47b-27bc-420f-89f1-3baeb281850b.PNG)

I have updates sysid tool and the newer versions have done nothing.

**Comment by calcmogul** [comment]
Something in the executable is linked against a different version of libwpiutil.so. It's usually vendordep versions.

**Comment by calcmogul** [comment]
OBE by #518.
