### ISSUE TITLE
UI freezes if robot program sends a lot of data

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/sysid#55]
Left my Romi spinning for 2 minutes on the quasistatic forward test, and it hard froze my desktop for 30s

**Comment by Piphi5** [comment]
I think we should just document that running a test for too long is a bad idea: https://github.com/wpilibsuite/frc-characterization/issues/195

**Comment by calcmogul** [comment]
Another option is stopping the test early (and somehow notifying the user of this so they can disable) before we gather too much data.

**Comment by Piphi5** [comment]
What if we had it so that if the vector is a certain size, it just stops collecting? And then the GUI can just notify the user that the data was only collected up to a certain point.

**Comment by calcmogul** [comment]
Sounds good to me.
