### ISSUE TITLE
Add Test Length Slider to filter data by time

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#75]
To reduce regression dilution.

**Comment by calcmogul** [comment]
Does this need to support trimming both sides, or just the right side?

**Comment by Piphi5** [comment]
I think just the right side since this would mainly be for the Dynamic test who has the left side automatically filtered.

**Comment by Piphi5** [comment]
Is there any advantage of doing this for the Quasistatic Tests?
