### ISSUE TITLE
Add csv download option to analyzer

### ISSUE THREAD

**Issue by Piphi5** [wpilibsuite/sysid#91]
This would make it easier to look at the raw data.

**Comment by prateekma** [comment]
Would this just convert the JSON into CSV format?

**Comment by calcmogul** [comment]
Basically, yeah.

**Comment by prateekma** [comment]
The format would be pretty straightforward for each test, but how would we incorporate all of the tests into one CSV? Should we save 4 CSVs, one for each test?

**Comment by Piphi5** [comment]
Maybe we could have an added column that specifies the test each entry is under.
